### PR TITLE
Added blog and showcase subdomain CNAME records

### PR DESCRIPTION
**Pull request by ryankurte**
Towards https://github.com/rust-embedded/rust-embedded-provisioning/issues/15

### CODE REVIEW

**Comment by nastevens** [comment]
r+

**Comment by adamgreig** [comment]
Ping @ryankurte / @nastevens, would it be possible to get this merged and deployed so we can start using the new URLs? Thanks!

**Comment by ryankurte** [comment]
sorry it took a moment, had to remember where my credentials were from... two years ago 🙃

Applied in 7ba0f60:
```
  # aws_route53_record.rust_embedded_org_blog will be created
  + resource "aws_route53_record" "rust_embedded_org_blog" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "blog.rust-embedded.org"
      + records         = [
          + "rust-embedded.github.io",
        ]
      + ttl             = 300
      + type            = "CNAME"
      + zone_id         = "Z1K6QDM5H6MZNC"
    }

  # aws_route53_record.rust_embedded_org_showcase will be created
  + resource "aws_route53_record" "rust_embedded_org_showcase" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "showcase.rust-embedded.org"
      + records         = [
          + "rust-embedded.github.io",
        ]
      + ttl             = 300
      + type            = "CNAME"
      + zone_id         = "Z1K6QDM5H6MZNC"
    }
```

And a `dig` show's they're there:
```
dig showcase.rust-embedded.org CNAME

; <<>> DiG 9.16.6-Ubuntu <<>> showcase.rust-embedded.org CNAME
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28838
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;showcase.rust-embedded.org.	IN	CNAME

;; ANSWER SECTION:
showcase.rust-embedded.org. 234	IN	CNAME	rust-embedded.github.io.

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Mar 03 11:17:55 NZDT 2021
;; MSG SIZE  rcvd: 92

```

Check that's working as you expect and we can close this?

**Comment by adamgreig** [comment]
Yep, looks good from here, thank you!

**Pull request merged**
